name: Deploy the backend
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code or cloning the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ## docker build and docker push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile/Dockerfile.backend
          push: true
          tags: himanshumishra3198/chalk-app-backend:${{ github.sha }}

      - name: Deploy to vm
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.107.102.79 -t "sudo docker system prune -af --volumes && sudo rm -rf /root/.cache && docker stop chalk_backend || true && docker rm -f chalk_backend || true && docker run --name chalk_backend -d -p 8080:8080 himanshumishra3198/chalk-app-backend:${{ github.sha }}"
