name: Deploy the frontend
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "Workflow triggered"

      - name: checkout the code or cloning the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ## docker build and docker push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile/Dockerfile.frontend
          build-args:
            - DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: himanshumishra3198/chalk-app-frontend:${{ github.sha }}

      - name: Deploy to vm
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.107.102.79 -t "docker stop chalk_frontend || true && docker rm chalk_frontend || true && docker run --name chalk_frontend -d -p 3000:3000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} himanshumishra3198/chalk-app-frontend:${{ github.sha }}"
