name: Deploy the websocket

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile/Dockerfile.ws
          push: true
          tags: himanshumishra3198/chalk-app-websocket:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Deploy to droplet
        run: |
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@128.199.27.128 << 'EOF'
            # Clean up old containers and cache
            docker system prune -af --volumes
            docker stop chalk_websocket 2>/dev/null && docker rm chalk_websocket 2>/dev/null || true
            # Run new container with restart policy
            docker run --name chalk_websocket -d --restart unless-stopped -p 8081:8081 \
              himanshumishra3198/chalk-app-websocket:${{ github.sha }}
          EOF
