name: Deploy the websocket

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile/Dockerfile.ws
          push: true
          tags: himanshumishra3198/chalk-app-websocket:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            REDIS_HOST=redis_server

      - name: Deploy to droplet
        run: |
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@128.199.27.128 << 'EOF'
            # Create network if not exists
            docker network inspect chalk_network >/dev/null 2>&1 || docker network create chalk_network

            echo "Pulling latest image..."
            docker pull himanshumishra3198/chalk-app-websocket:${{ github.sha }}
            echo "Stopping and removing old container..."

            # Clean up old containers
            docker stop chalk_websocket 2>/dev/null && docker rm chalk_websocket 2>/dev/null || true
            
            # Run new container attached to chalk_network
            docker run --name chalk_websocket --network chalk_network -d --restart unless-stopped -p 8081:8081 \
              -e REDIS_HOST=redis_server \
              himanshumishra3198/chalk-app-websocket:${{ github.sha }}
          EOF
